### ISSUE TITLE
bat file for downloading from windows

### ISSUE THREAD

**Issue by elaheyenaz65** [SilvioGiancola/SoccerNet-code#12]
Hi @SilvioGiancola,
Is there any .bat file for downloading the data from windows? A file for replacing SoccerNet_CSV_Downloader.sh 
Thank you!

**Comment by SilvioGiancola** [comment]
Hi @elaheyenaz65 ,
Unfortunately there is no .bat to download the data on windows. However, as far as I know windows now has a linux terminal, that you should be able to use.
Best of luck
