### ISSUE TITLE
Permission denied: Maybe you need to change permission over 'Anyone with the link'?

### ISSUE THREAD

**Issue by Edwardf0t1** [SilvioGiancola/SoccerNet-code#13]
Hi Silvio,

I find your project is very interesting. However, when I run the script to download data
./src/SoccerNet_CSV_Downloader.sh data/SoccerNet_V1.1_Features.csv

I got permission issues. For example:

Parsing 1pl4lEo2sMW0R29bBZbzYmvPUvUgvtrnb into data/spain_laliga/2016-2017/2017-04-02 - 17-15 Real Madrid 3 - 0 Alaves/1_I3D.npy 
Permission denied: https://drive.google.com/uc?id=1pl4lEo2sMW0R29bBZbzYmvPUvUgvtrnb
Maybe you need to change permission over 'Anyone with the link'?

I checked my internet connection, and it seems ok. Just wonder if the data is still available? Thanks.

**Comment by SilvioGiancola** [comment]
Hi @Edwardf0t1 ,

Google Drive has a maximum bandwidth of 10TB/day. As of today, I am able to download this specific file in incognito mode, so you should be able to do so too.

Cheers,
