### ISSUE TITLE
How can I get labels_Delta_.json?

### ISSUE THREAD

**Issue by Dondkeman** [SilvioGiancola/SoccerNet-code#17]
First, thank you for providing useful dataset and code.

I have tried to get more accurately chunk classification. 
and now, I try to evaluate new trained model for spotting task.
but, I couldn't correctly running evaluation code.

Generation of predictions_00_(Argmax/NMS/Center_00.json was success.
but, I can't running 'get_detection_performance_spotting', because labels_Delta_.json files.

I read this comment
https://github.com/SilvioGiancola/SoccerNet-code/issues/6#issuecomment-613969675
from closed issues page.

How can I get(or generate?) labels_Delta_.json ??

Thank you.

**Comment by SilvioGiancola** [comment]
You can copy the structure from your prediction in the json format, and create the labels_Delta_.json from Labels.json for each delta. Basically, Labels.json is for spotting (single timestamp) while labels_Delta_.json is for activities (start/end timestamp).
Then I used the code from ActivityNet to estimate the mAP with tIoU>0 for each deltas.

Alternatively, look at this repo: https://github.com/cioppaanthony/context-aware-loss there is a function for the [spotting evaluation](https://github.com/cioppaanthony/context-aware-loss/blob/5d31d57f8b9ca6669a08c5521d1dbb9a3f104955/utils/evaluation.py#L370) (Average-mAP) that avoid this transformation from spotting to activities.

**Comment by Dondkeman** [comment]
That was very helpful, thank you.
