### ISSUE TITLE
Correct links for gdown

### ISSUE THREAD

**Issue by agirbau** [SilvioGiancola/SoccerNet-code#2]
Hello! 
I think you made a typo on calling gdown for collecting data, it should be (e.g.):
./gdown.pl https://drive.google.com/file/d/1FDyrfnp8dsF7cd_NyzdTHA-EFIK_TvKK/view?usp=sharing/data/SoccerNet_V1.1_Features.zip

Is this correct?

**Comment by agirbau** [comment]
OK, my bad, I was the one calling it wrongly ^^

**Comment by SilvioGiancola** [comment]
Hi agirbau,
To clear any doubt, `gdown.pl` needs 2 arguments, the first one is the url of the google drive file, the second one is the local path where the file will be downloaded. 
Note that you may need a fast connection, there is almost 120GB of data. 
You may want to visit the google drive link to check the data structure and download a single file.
Cheers
