### ISSUE TITLE
Train and test split

### ISSUE THREAD

**Issue by agirbau** [SilvioGiancola/SoccerNet-code#3]
Hello, I have a question regarding the split between train, validation and test. Are these marked somehow? Could you explain which ones did you use when implementing the paper? Thank you!

**Comment by SilvioGiancola** [comment]
Dear agirbau,

The list of games I used in the SoccerNet paper for training, validation and testing are now available in the 3 numpy files:
`src/listgame_Train_300.npy` (list of 300 games for training) 
`src/listgame_Valid_100.npy` (list of 100 games for validation)
`src/listgame_Test_100.npy` (list of 100 games for testing)

Also, check `src/ReadSplitData.py`, I provide a way to reads the numpy files and loop over the list of games.

`python src/ReadSplitData.py data src/listgame_Train_300.npy`
