### ISSUE TITLE
can't find listgame_Train_300.npy,listgame_Test_100.npy,listgame_Valid_100.npy

### ISSUE THREAD

**Issue by tianyilt** [SilvioGiancola/SoccerNet-code#4]
None of them are in "data/". But I find them in commit history "add train/valid/test split according to the SoccerNet paper". Why they are removed later ? Could you take them back, thank you.

**Comment by tianyilt** [comment]
i have create a pull request

**Comment by SilvioGiancola** [comment]
I brought back the list of the games used in the SoccerNet paper for training, validation and testing, they have been deleted for no reason. Thanks for raising that issue.
