### ISSUE TITLE
i3d. py and rgb_scratch - rgb_imagenet checkpoints

### ISSUE THREAD

**Issue by draxler1** [SilvioGiancola/SoccerNet-code#8]
Dear Sir,
I am trying to use feature_extractor using i3d script you provide. 
Line number 20 in extract_i3d_spatial_features.py that is "import i3d" not working, can ypu please provide me i3d.py class file in your repository.

Also,
```
_CHECKPOINT_PATHS = {
    'rgb': 'kinetics-i3d/data/checkpoints/rgb_scratch/model.ckpt',
    'rgb_imagenet': 'kinetics-i3d/data/checkpoints/rgb_imagenet/model.ckpt'
}
```
are missing in main deepmind kinetic-i3d repository. Those folder contained:
checkpoint
model.ckpt.data-00000-of-00001	
model.ckpt.index
model.ckpt.meta

can you please share 'kinetics-i3d/data/checkpoints/rgb_scratch/model.ckpt' and 'kinetics-i3d/data/checkpoints/rgb_imagenet/model.ckpt'

Thanks.

**Comment by SilvioGiancola** [comment]
Dear @draxler1,

Make sure you have cloned the SoccerNet-code repo with the kinetics-i3d submodule, or re-initialize the submodule, that's the reason of your issue importing i3d, your kinetics-i3d folder looks empty to me be empty.

The code for feature extraction originate from its [original github repo](https://github.com/deepmind/kinetics-i3d), I have added it here as a submodule. The models your are looking for are available [here](https://github.com/deepmind/kinetics-i3d/tree/master/data/checkpoints/rgb_scratch) and [here](https://github.com/deepmind/kinetics-i3d/tree/master/data/checkpoints/rgb_imagenet). 

I recommend you to use the feature provided with the the dev kit as I3D require 8 GPUs for the flow estimation and is extremely slow. If you insist on extracting your own features, you can follow the instruction on the [kinetics-i3d repo](https://github.com/deepmind/kinetics-i3d) as they may have released new models trained on kinetics-600.

Best

**Comment by SilvioGiancola** [comment]
PS: you should be able to initialize the submodule kinetics-i3d by running `git submodule update --init --recursive`

**Comment by SilvioGiancola** [comment]
Actually, you should clone the I3D repo following [those instructions](https://github.com/SilvioGiancola/SoccerNet-code/tree/master/src/feature_extraction#i3d).

**Comment by draxler1** [comment]
Thanks for quick response @SilvioGiancola 
I have followed exactly what you specified in reply. Now, following error popping up.

```
File "extract_i3d_spatial_features.py", line 232, in <module>
    main(args.video_list_dir, args.feature_dir, overwrite=args.overwrite)  File "extract_i3d_spatial_features.py", line 104, in main
    _NUM_CLASSES, spatial_squeeze=True, final_endpoint='PreLogits')
  File "/floyd/home/src/feature_extraction/i3d-feat-extract/i3d.py", line 137, in __init__
    raise ValueError('Unknown final endpoint %s' % final_endpoint)
ValueError: Unknown final endpoint PreLogits

Seeking help :-(
```

**Comment by SilvioGiancola** [comment]
I'm sorry, but I can't provide support to extract I3D features as it is not the scope of SoccerNet and it's not my code but rather [deepmind's](https://github.com/deepmind/kinetics-i3d). Please check with them to run it on your own videos. I am already providing the [I3D features](https://drive.google.com/drive/folders/1qkIeQCGaHg0_CUCHvh3hQFTlq26D20Ts?usp=sharing) for all the videos of SoccerNet [[pre-zipped here](https://drive.google.com/file/d/1FDyrfnp8dsF7cd_NyzdTHA-EFIK_TvKK/view?usp=sharing)].
